default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: users_db
  username: postgres
  password: postgres

development:
  <<: *default
  database: users_service_development

test:
  <<: *default
  database: users_service_test

production:
  <<: *default
  database: users_service_production
